import PersistentWebsocket from './PersistentWebsocket';
import StateBuilder from './StateBuilder';
import { NoConnectionListener, TempInstance, Listener, Model, InstanceListener, InstanceType, Writable } from './ContextChannel.interfaces';
import { Action, ActionResponse, ActionIndex, CallPromise, WriteMessage, WriteResponse, WriteIndex, WriteError } from './actions.d';

/**
 * Base class for generated TypeScript channel classes.
 *
 * ContextChannel manages the WebSocket connection to a Django ContextChannel,
 * handles authentication, receives state updates, and provides methods for
 * calling backend actions via RPC.
 *
 * Subclasses are auto-generated by `makefrontend` and provide typed action
 * methods matching the Django `@action` decorated methods.
 *
 * @template T - The type of the root/anchor state object
 * @template Y - The type of the runtime state (optional)
 *
 * @example
 * ```typescript
 * // Generated channel usage
 * const channel = new MyContextChannel(authToken);
 * channel.args = { projectId: 123 };
 *
 * // React hook integration
 * const { state, connected } = useChannelState(channel);
 *
 * // Call backend action
 * const result = await channel.updateStatus("active");
 * ```
 */
abstract class ContextChannel<T, Y=unknown> {
  private ws: PersistentWebsocket | undefined;
  private builder: StateBuilder<T> | undefined;
  private listeners: Listener<T>[] = [];
  private instance_listeners: { [key: string]: InstanceListener } = {};
  private runtimeListeners: Listener<Y>[] = [];
  private noConnectionListeners: NoConnectionListener[] = [];
  private activeCalls: ActionIndex = {};
  private activeWrites: WriteIndex = {};
  private tempIdCounter: number = -1;
  private token: string;

  protected args: { [key: string]: number | string } = {};

  abstract endpoint: string;
  abstract anchor: string;
  abstract baseURL: string;
  abstract model: Model;
  abstract many: boolean;
  abstract runtimeState: Y | undefined | null;
  public writable: Writable = {};

  public connected: boolean = false;
  public onConnected: () => void = () => {};
  public onEmpty: () => void = () => {};
  public onError: (error: Error) => void = () => {};

  /**
   * Creates a new channel instance.
   *
   * @param token - The Django REST Framework auth token for authentication
   */
  constructor(token: string) {
    this.token = token;
  }

  /**
   * Initializes the WebSocket connection and state builder.
   *
   * Called automatically on first `subscribe()`. Sets up the PersistentWebsocket,
   * wires message handlers, and creates the StateBuilder for state reconstruction.
   */
  public init() {
    if (this.builder)
      return;

    const writeCallbacks = Object.keys(this.writable).length > 0 ? {
      saveInstance: this.saveInstance.bind(this),
      createInstance: this.createInstance.bind(this),
      deleteInstance: this.deleteInstance.bind(this),
    } : undefined;
    this.builder = new StateBuilder<T>(this.model, this.anchor, this.many, this.writable, writeCallbacks);
    const ws = new PersistentWebsocket(this.getEndpoint(), this.token);

    ws.onClose = this.onclose.bind(this);
    ws.onOpen = this.onopen.bind(this);

    ws.onInstances = (instances) => {
      this.receiveInstances(instances);
    };

    ws.onActionResponse = (response) => {
      this.receiveActionResponse(response);
    };

    ws.onWriteResponse = (response) => {
      this.receiveWriteResponse(response);
    };

    ws.onRuntimeStateChange = (message) => {
      const msg = message as { type: 'runtimeVar'; var: keyof Y; value: unknown };
      const runtimeVar = msg.var;
      const value = msg.value;
      this.receiveRuntimeState(runtimeVar, value);
    };

    ws.onAnchorPrepend = (anchorId) => {
      this.prependAnchor(anchorId);
    }

    ws.onInitialAnchors = (anchorIds) => {
      this.builder!.setAnchors(anchorIds);
      this.notify();
    }

    ws.onConnected = this.onConnected;
    ws.onError = this.onError;
    ws.onEmpty = this.onEmpty;

    this.ws = ws;
  }

  /** Gracefully close the WebSocket connection. */
  public disconnect() {
    this.ws?.disconnect('manual-disconnect');
  }

  /**
   * Process incoming instances from the server and notify listeners.
   */
  private receiveInstances(instances: TempInstance[]) {
    this.builder!.update(instances);

    for (const instance of instances) {
      this.notifyInstance(instance);
    }

    this.notify();
  }

  private receiveRuntimeState(runtimeVar: keyof Y, value: unknown) {
    this.runtimeState = { ...this.runtimeState, [runtimeVar]: value } as Y;
    this.notifyRuntimeState();
  }

  private prependAnchor(anchorId: number) {
    this.builder!.prependAnchorId(anchorId);
    this.notify()
  }

  private notifyInstance(instance: InstanceType) {
    const key = `${instance._instance_type}:${instance.id}`;
    const listener = this.instance_listeners[key];
    if (listener) {
      listener(this.builder!.getInstance(key));
    }
  }

  private notify() {
    const state = this.builder!.state;
    for (const listener of this.listeners) {
      if (state) listener(state as T);
    }
  }

  private notifyRuntimeState() {
    for (const listener of this.runtimeListeners) {
      if (this.runtimeState) listener(this.runtimeState);
    }
  }

  /**
   * Subscribe to state changes. Automatically connects the WebSocket on first subscriber.
   *
   * @param listener - Callback invoked with the new state on every update
   * @param noConnectionListener - Optional callback invoked with connection loss/restore timestamps
   * @returns Unsubscribe function. When the last subscriber unsubscribes, the WebSocket disconnects.
   */
  public subscribe(listener: Listener<T>, noConnectionListener?: NoConnectionListener): () => void {
    if (!this.ws)
      this.init();

    this.listeners.push(listener);

    if (noConnectionListener) {
      this.noConnectionListeners.push(noConnectionListener);
    }

    if (this.listeners.length === 1)
      this.ws!.connect();

    const unsubscribe = () => {
      const index = this.listeners.indexOf(listener);
      if (index !== -1) {
        this.listeners.splice(index, 1);
        if (this.listeners.length === 0)
          this.ws!.disconnect('no-subscribers');
      }
    };

    return unsubscribe;
  }

  /**
   * Subscribe to changes on a specific instance.
   *
   * @param listener - Callback invoked when the instance is updated
   * @param instance_id - The ID of the instance to watch
   * @param instance_type - The `_instance_type` string (e.g. 'myapp.serializers.TaskSerializer')
   * @returns Unsubscribe function
   */
  public subscribeInstance(listener: InstanceListener, instance_id: number, instance_type: string) {
    const key = `${instance_type}:${instance_id}`;
    this.instance_listeners[key] = listener;
    const unsubscribe = () => {
      delete this.instance_listeners[key];
    };

    if (!this.builder) return unsubscribe;

    try {
      const instance = this.builder!.getInstance(key);
      this.notifyInstance(instance);
    } catch (_e) {
      return unsubscribe;
    }

    return unsubscribe;
  }

  /**
   * Get a specific instance from the state by type and ID.
   *
   * @param instance_type - The `_instance_type` string
   * @param instance_id - The instance ID
   * @returns The instance, or null if not found
   */
  public getInstance<Y = InstanceType>(instance_type: string, instance_id: number): Y | null {
    const key = `${instance_type}:${instance_id}`;
    try {
      return this.builder!.getInstance(key) as Y;
    } catch (_err) {
      return null;
    }
  }

  /**
   * Subscribe to runtime state changes (server-pushed variables).
   *
   * @param listener - Callback invoked with the updated runtime state
   * @returns Unsubscribe function
   */
  public subscribeRuntimeState(listener: Listener<Y>): () => void {
    this.runtimeListeners.push(listener);

    const unsubscribe = () => {
      const index = this.runtimeListeners.indexOf(listener);
      if (index !== -1) {
        this.runtimeListeners.splice(index, 1);
      }
    };
    return unsubscribe;
  }

  /**
   * Call a backend @action method via WebSocket RPC.
   *
   * Used by generated subclass methods to invoke Django ContextChannel actions.
   *
   * @param action - The snake_case action method name
   * @param params - Array of parameters to pass to the action
   * @returns Promise resolving with the action's return value
   */
  protected async callAction<T>(action: string, params: any[]): Promise<T> {
    const callId = this.generateUniqueId();
    const cmd: Action = { callId, action, params };
    const activeCalls = this.activeCalls;
    return new Promise((resolve, reject) => {
      activeCalls[callId] = {resolve, reject} as CallPromise<T>;
      this.ws?.send(JSON.stringify(cmd));
    });
  }

  private receiveActionResponse<T>(response: ActionResponse<T>) {
    const promise = this.activeCalls[response.callId];
    if (!promise) {
        console.error(`Received a response for unmatched callId: ${response.callId}`);
        return;
    }
    if (response.error) {
      promise.reject(response.error);
    } else if (response.result !== undefined) {
      promise.resolve(response.result as T);
    } else {
      promise.reject({ code: 500, message: 'Malformed action response: missing both result and error' });
    }
    delete this.activeCalls[response.callId];
  }

  private receiveWriteResponse(response: WriteResponse) {
    const promise = this.activeWrites[response.writeId];
    if (!promise) {
      console.error(`Received a write response for unmatched writeId: ${response.writeId}`);
      return;
    }
    if (response.success) {
      promise.resolve();
    } else if (response.error) {
      promise.reject(response.error);
    } else {
      promise.reject({ code: 500, message: 'Malformed write response: missing both success and error' });
    }
    delete this.activeWrites[response.writeId];
  }

  async saveInstance(instanceType: string, instanceId: number, data: Record<string, unknown>): Promise<void> {
    const writeId = this.generateUniqueId();
    const optimisticKey = `${instanceType}:${instanceId}`;

    const previousState = this.builder?.getRawInstance(optimisticKey);
    if (previousState) {
      this.builder?.applyOptimisticUpdate(instanceType, instanceId, data);
      this.notify();
    }

    const cmd: WriteMessage = {
      type: 'write',
      writeId,
      operation: 'save',
      instanceType,
      instanceId,
      data,
    };

    return new Promise((resolve, reject) => {
      this.activeWrites[writeId] = {
        resolve: () => {
          resolve();
        },
        reject: (error: WriteError) => {
          if (previousState) {
            this.builder?.rollbackOptimisticUpdate(instanceType, instanceId, previousState);
            this.notify();
          }
          reject(error);
        },
      };
      this.ws?.send(JSON.stringify(cmd));
    });
  }

  async createInstance(
    instanceType: string,
    parentType: string,
    parentId: number,
    relationName: string,
    data: Record<string, unknown> = {},
  ): Promise<number> {
    const writeId = this.generateUniqueId();
    const tempId = this.tempIdCounter--;

    this.builder?.addTempInstance(instanceType, tempId, parentType, parentId, relationName, data);
    this.notify();

    const cmd: WriteMessage = {
      type: 'write',
      writeId,
      operation: 'create',
      instanceType,
      parentType,
      parentId,
      relationName,
      data,
    };

    return new Promise((resolve, reject) => {
      this.activeWrites[writeId] = {
        resolve: () => {
          resolve(tempId);
        },
        reject: (error: WriteError) => {
          this.builder?.removeTempInstance(instanceType, tempId);
          this.notify();
          reject(error);
        },
      };
      this.ws?.send(JSON.stringify(cmd));
    });
  }

  async deleteInstance(instanceType: string, instanceId: number): Promise<void> {
    const writeId = this.generateUniqueId();
    const optimisticKey = `${instanceType}:${instanceId}`;

    const previousState = this.builder?.getRawInstance(optimisticKey);
    const parentInfo = this.builder?.getParentInfo(optimisticKey);

    if (previousState) {
      this.builder?.applyOptimisticDelete(instanceType, instanceId);
      this.notify();
    }

    const cmd: WriteMessage = {
      type: 'write',
      writeId,
      operation: 'delete',
      instanceType,
      instanceId,
    };

    return new Promise((resolve, reject) => {
      this.activeWrites[writeId] = {
        resolve: () => {
          resolve();
        },
        reject: (error: WriteError) => {
          if (previousState && parentInfo) {
            this.builder?.rollbackOptimisticDelete(
              instanceType,
              instanceId,
              previousState,
              parentInfo.parentType,
              parentInfo.parentId,
              parentInfo.relationName,
            );
            this.notify();
          }
          reject(error);
        },
      };
      this.ws?.send(JSON.stringify(cmd));
    });
  }

  private getEndpoint(): string {
    let constructedEndpoint = this.endpoint;

    // Use a regex to find all the placeholders
    const matches = this.endpoint.match(/{\w+}/g);

    if (matches) {
      matches.forEach((match) => {
        // Extract the property name from the placeholder
        const propertyName = match.replace(/[{}]/g, "");
        const propertyValue = this.args[propertyName];

        // Substitute the placeholder with the property value, if it exists
        constructedEndpoint = constructedEndpoint.replace(match, propertyValue.toString());
      });
    }

    return `${this.baseURL}${constructedEndpoint}`;
  }

  private onopen() {
    for (const listener of this.noConnectionListeners) {
      listener(undefined);
    }
  }

  private onclose() {
    const now = new Date();
    for (const listener of this.noConnectionListeners) {
      listener(now);
    }
  }

  private idCounter: number = 0;

  private generateUniqueId(): number {
    const now = new Date().getTime();
    this.idCounter = (this.idCounter + 1) % 1000000;
    return now * 1000000 + this.idCounter;
  }
}


export default ContextChannel;
