# Generated by Django 4.2.2 on 2023-08-30 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('react_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_set', to='react_test.job')),
            ],
        ),
    ]
