name: "@rxdjango/react Tests"
on:
  workflow_call:
  pull_request:
    branches: ["main"]
    paths:
      - "rxdjango-react/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: RunTesting @rxdjango/react
        uses: ./.github/actions/tests/react

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Running build @rxdjango/react
        uses: ./.github/actions/build/react
